Feature/auto poll deactivation upon meeting proposal approval-quorum
DrSam/flowback-backend pull request #13
Opened 2024-05-13 17:43 UTC by jayapal

2024-05-16 13:01 UTC, Gofven requested changes
There's plenty of things that needs to be revised before accepting this pull request, although there are some nice additions i can see that you've added c:

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
> +    total_community_members = Group.objects.get(id=poll_community.id).groupuser_set.count()
Omit people with active=False

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
> +        poll.status = 1
Setting poll.status = 1 means the poll has finished (which should only be set after poll finished counting)

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
Remove prints if you don't use them anymore, these will litter the console, alternatively you can send debug log info to django using logging module https://docs.djangoproject.com/en/4.2/howto/logging/

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/proposal.py
> +    check_poll_proposal_met_approval_and_quorum(proposal_id=proposal_id)
This shouldn't be here (if it's checking poll_proposal), this should be counted at proposal_end_date, and iterate trough every proposal

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/models.py
> +    approval_minimum = models.PositiveIntegerField(default=None, null=True, blank=True)
No checks found for approval minimum, must be below 100

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
> +        return False
Approval minimum will never pass unless set, either make it required or True

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
> +        return False
Quorum will never pass unless set, either make it required or True

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
> +    Determines whether a poll proposal has achieved the necessary approval and quorum to become inactive.
Active, not inactive
Also it's poll, not poll proposal

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/proposal.py
> +    check_poll_proposal_met_approval_and_quorum(proposal_id=proposal_id)
Additionally statement does nothing aside from changing wrong variable (see above)

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
> +def check_poll_proposal_met_approval_and_quorum(*,proposal_id:int) -> bool:
poll, not poll_proposal

2024-05-16 13:01 UTC, Gofven commented on flowback/poll/services/poll.py
Additionally you seem to have mixed up poll_proposal and poll, i'm not sure if you wish to check approval_minimum for poll or proposal?

2024-05-16 13:01 UTC, Gofven commented on notes
Unnessesary file, delete or exclude from vcs

2024-05-16 13:01 UTC, Gofven commented on .DS_Store
Unnessesary, add to .gitignore

2024-05-17 15:37 UTC, pvfarooq commented on notes
@narendersaini32

2024-05-17 15:51 UTC, pvfarooq commented on flowback/poll/services/poll.py
Yes, I was checking the approval minimum for the poll. The function name was misleading (renamed it). However, the way it works is correct.

2024-05-24 08:15 UTC, jayapal commented on flowback/poll/services/poll.py
> +    total_community_members = Group.objects.get(id=poll_community.id).groupuser_set.count()
This has been fixed by adding a active filter in the query.

2024-05-24 08:16 UTC, pvfarooq commented on flowback/poll/services/poll.py
> +    total_community_members = Group.objects.get(id=poll_community.id).groupuser_set.count()
This has been fixed by adding an active filter in the query.

2024-05-24 08:19 UTC, pvfarooq commented on flowback/poll/services/poll.py
> +        poll.status = 1
I've introduced a new poll status, '2', to represent the 'finalization_period'. When a poll meets the quorum and gains approval, its status will be updated to '2'. However, if a user downvotes the proposal and this results in the poll no longer meeting the quorum or approval criteria, the status will revert to '0' (ongoing).

2024-05-24 08:20 UTC, pvfarooq commented on flowback/poll/models.py
> +    approval_minimum = models.PositiveIntegerField(default=None, null=True, blank=True)
I've added the min and max value validator for the field.

2024-05-24 08:21 UTC, pvfarooq commented on notes
Removed

2024-05-24 08:53 UTC, pvfarooq commented on flowback/poll/services/poll.py
> +        return False
Made the fields mandatory with a default value of 51 for approval and quorum

2024-05-24 08:53 UTC, pvfarooq commented on flowback/poll/services/poll.py
> +    Determines whether a poll proposal has achieved the necessary approval and quorum to become inactive.
Updated

2024-05-24 08:53 UTC, pvfarooq commented on flowback/poll/services/poll.py
> +def check_poll_proposal_met_approval_and_quorum(*,proposal_id:int) -> bool:
Updated

2024-05-24 08:55 UTC, pvfarooq commented on flowback/poll/services/poll.py
> +        return False
Updated

2024-05-24 08:55 UTC, pvfarooq commented on .DS_Store
Removed

2024-05-28 12:56 UTC, Gofven approved these changes

2024-06-04 15:44 UTC, Gofven commented on flowback/poll/services/proposal.py
> +    check_poll_met_approval_and_quorum(proposal_id=proposal_id)
this should be checked elsewhere to ensure it'll be run reliably c:

2024-06-06 15:06 UTC, merged